# Generated by Django 3.1.1 on 2020-09-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='favorite',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
